version: '3'

services:

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_API_SELECT_PARQUET: ${MINIO_API_SELECT_PARQUET}
    volumes:
      - ${DATADIR}/minio/data:/data
      - ${DATADIR}/minio/config:/root/.minio
      - ./scripts:/scripts
    # command: server /data
    entrypoint: /bin/sh
    command: scripts/init.sh